---
- hosts: jumphost
  pre_tasks:
     - include: './tasks/set-sysctl.yml'
     - include: './tasks/enable-dhcpdv4.yml'
  roles:
     - { role: MichaelRigart.interfaces, become: true }
     - { role: bertvv.dhcp }
  handlers:
      - include: './handlers/services.yml'
