---
- name: Install packages
  hosts: '{{ target  }}'
  become: true
  # Add Users 
  vars_files:
  - "./devices/group_vars/{{ target  }}.yml"
  handlers:
  - include: './handlers/services.yml'
  tasks: 
  - include: './tasks/install-base.yml'
  - include: './tasks/create-users.yml'
  roles:
  - ossobv.salt-minion-playbook
