- hosts: jumphost,docker01.in.ffmuc.net,docker02.in.ffmuc.net

  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: latest
    pip_install_packages:
      - name: docker
      - name: docker-compose

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - include: './tasks/manage-containers.yml'
