---
- name: Install packages
  hosts: '{{ target  }}'
  become: true
  # Add Users 
  vars_files:
  - "./devices/group_vars/{{ target  }}.yml"
  tasks: 
  - include: './tasks/install-base.yml'
  - include: './tasks/create-users.yml'
