- name: geerlingguy.glusterfs
  src: geerlingguy.glusterfs
- name: bertvv.dhcp
  src: bertvv.dhcp
- name: geerlingguy.ntp
  src: geerlingguy.ntp
- name: lae.proxmox
  src: lae.proxmox
- name: MichaelRigart.interfaces
  version: develop
  src: https://github.com/awlx/ansible-role-interfaces/archive/fix_bonding_and_vlans.tar.gz
- name: geerlingguy.jenkins
  src: geerlingguy.jenkins
- name: Stout.openvpn
  version: develop
  src: https://github.com/awlx/Stouts.openvpn/archive/develop.tar.gz
