- name: GlusterFS Role
  src: geerlingguy.glusterfs
- name: Interface Management Role
  src: MichaelRigart.interfaces
- name: NTP Role
  src: geerlingguy.ntp
- name: Proxmox Role
  src: lae.proxmox
- name: DHCP role
  src: https://github.com/awlx/ansible-role-interfaces/archive/fix_bonding_and_vlans.tar.gz
- name: geerlingguy.jenkins
  src: geerlingguy.jenkins
