- name: geerlingguy.glusterfs
  src: geerlingguy.glusterfs
- name: geerlingguy.ntp
  src: geerlingguy.ntp
- name: lae.proxmox
  src: lae.proxmox
- name: MichaelRigart.interfaces
  src: https://github.com/awlx/ansible-role-interfaces/archive/fix_bonding_and_vlans.tar.gz
- name: geerlingguy.jenkins
  src: geerlingguy.jenkins
