---
- name: "Loading kernel modules"
  modprobe: 
    name: "{{ item }}"
    state: present
  loop: 
    - ib_ipoib
    - ib_umad
- name: "Adding kernel modules to boot config"
  copy:
    src: './files/etc/modules-load.d/infiniband.conf'
    dest: '/etc/modules-load.d/infiniband.conf'
    owner: root
    group: root
    mode: 0744
- name: "Enable service opensm"
  systemd:
    state: started
    enabled: yes
    name: opensm
