---
- name: Git clone Netbox
  git:
      repo: 'https://github.com/ninech/netbox-docker.git'
      dest: '/srv/docker/netbox'
- name: Install or Upgrade Netbox
  docker_service:
      project_name: netbox
      files: './docker-compose/netbox-compose.yml'
