---
- name: Create Netbox directory
  file:
      path: /srv/docker/netbox
      state: directory
      mode: 0755
- name: Git clone Netbox
  git:
      repo: 'https://github.com/ninech/netbox-docker.git'
      dest: '/srv/docker/netbox'

- name: Copy compose file
  copy:
      src: './files/netbox-compose.yml'
      dest: '/srv/docker/netbox/netbox-ansible-compose.yml'

- name: Install or Upgrade Netbox
  docker_service:
      project_name: netbox
      project_src: '/srv/docker/netbox'
      files: 'netbox-ansible-compose.yml'
