all:
    children:
        proxmox:
            hosts:
                dc1:
                    ansible_host: dc1
                dc2: 
                    ansible_host: dc2
                dc3:
                    ansible_host: dc3
