all:
    children:
        jumphost:
            hosts:
                guardian:
                    ansible_host: guardian.ffmuc.net
        kvm:
            hosts:
                vm-host01.in.ffmuc.net:
                    ansible_host: vm-host01.in.ffmuc.net
                vm-host02.in.ffmuc.net: 
                    ansible_host: vm-host02.in.ffmuc.net
        proxmox:
            hosts:
               proxmox.in.ffmuc.net:
                    ansible_host: proxmox.in.ffmuc.net
        buildserver:
            hosts:
                buildserver.in.ffmuc.net:
                    ansible_host: buildserver.in.ffmuc.net
        stuff:
            hosts:
                librenms.in.ffmuc.net:
                    ansible_host: librenms.in.ffmuc.net
                cr01.in.ffmuc.net:
                    ansible_host: cr01.in.ffmuc.net 
