all:
    children:
        jumphost:
            hosts:
                guardian:
                    ansible_host: guardian.ffmuc.net
        kvm:
            hosts:
                vm-host01.in.ffmuc.net:
                    ansible_host: vm-host01.in.ffmuc.net
                vm-host02.in.ffmuc.net: 
                    ansible_host: vm-host02.in.ffmuc.net
                vm-host03.in.ffmuc.net:
                    ansible_host: vm-host03.in.ffmuc.net
                vm-host04.in.ffmuc.net:
                    ansible_host: vm-host04.in.ffmuc.net
        proxmox:
            hosts:
               proxmox.in.ffmuc.net:
                    ansible_host: proxmox.in.ffmuc.net
       stuff:
            hosts:
                librenms.in.ffmuc.net:
                    ansible_host: librenms.in.ffmuc.net
                cr01.in.ffmuc.net:
                   ansible_host: cr01.in.ffmuc.net
                dns01.in.ffmuc.net:
                    ansible_host: dns01.in.ffmuc.net
                docker01.in.ffmuc.net:
                    ansible_host: docker01.in.ffmuc.net
                docker02.in.ffmuc.net:
                    ansible_host: docker02.in.ffmuc.net
                webfrontend01.in.ffmuc.net:
                    ansible_host: webfrontend01.in.ffmuc.net
                webfrontend02.in.ffmuc.net:
                    ansible_host: webfrontend02.in.ffmuc.net
                cr02.in.ffmuc.net:
                    ansible_host: cr02.in.ffmuc.net
                guardian-exa.in.ffmuc.net:
                    ansible_host: guardian-exa.in.ffmuc.net
                buildserver.in.ffmuc.net:
                    ansible_host: buildserver.in.ffmuc.net
